### ISSUE TITLE
Link to the Blender addon code dead

### ISSUE THREAD

**Issue by mpreisler** [moyalmic/Blender-Grass-Animator#1]
The link in `dokumentace2.adoc` is dead:
https://github.com/moyalmic/Blender-Grass-Animator/blob/master/3D/dokumentace2.adoc#odkaz-na-sta%C5%BEen%C3%AD

Probably meant to say https://github.com/moyalmic/Blender-Grass-Animator/blob/master/3D/res2.zip instead of https://github.com/moyalmic/Blender-Grass-Animator/blob/master/3D/res1.zip

**Comment by moyalmic** [comment]
Thanks for the heads up, link has been fixed and hopefully works now!
